# Generated by Django 5.2.17 on 2026-09-30 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=300, verbose_name='书名')),
                ('author', models.CharField(blank=True, max_length=300, verbose_name='作者')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='出版社')),
                ('published_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='出版年')),
                ('cover_url', models.URLField(blank=True, max_length=1000, verbose_name='封面链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editions', to='catalog.category', verbose_name='分类')),
                ('tags', models.ManyToManyField(blank=True, related_name='editions', to='catalog.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '图书版本',
                'verbose_name_plural': '图书版本',
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='存放位置')),
                ('status', models.CharField(choices=[('unread', '未读'), ('reading', '在读'), ('read', '已读'), ('loaned', '借出')], default='unread', max_length=12, verbose_name='阅读状态')),
                ('acquired_on', models.DateField(blank=True, null=True, verbose_name='入藏日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='catalog.edition', verbose_name='图书版本')),
            ],
            options={
                'verbose_name': '馆藏副本',
                'verbose_name_plural': '馆藏副本',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
