# Generated by Django 5.2.17 on 2026-09-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='title',
            field=models.CharField(blank=True, max_length=300, verbose_name='书名'),
        ),
    ]
