# Generated by Django 5.2.17 on 2026-10-01 00:10

from django.db import migrations, models


def categories_to_tags(apps, schema_editor):
    Category = apps.get_model('catalog', 'Category')
    Edition = apps.get_model('catalog', 'Edition')
    Tag = apps.get_model('catalog', 'Tag')
    database = schema_editor.connection.alias
    categories = {
        pk: (name, parent_id)
        for pk, name, parent_id in Category.objects.using(database).values_list('pk', 'name', 'parent_id')
    }
    if not categories:
        return

    Tag.objects.using(database).bulk_create(
        [Tag(name=name) for name, _ in categories.values()], ignore_conflicts=True,
    )
    tag_ids = dict(Tag.objects.using(database).filter(
        name__in=[name for name, _ in categories.values()],
    ).values_list('name', 'pk'))
    through = Edition.tags.through
    links = []
    for edition_id, category_id in Edition.objects.using(database).exclude(
            category_id__isnull=True).values_list('pk', 'category_id').iterator(chunk_size=500):
        seen = set()
        while category_id in categories and category_id not in seen:
            seen.add(category_id)
            name, category_id = categories[category_id]
            links.append(through(edition_id=edition_id, tag_id=tag_ids[name]))
        if len(links) >= 1000:
            through.objects.using(database).bulk_create(links, ignore_conflicts=True)
            links.clear()
    if links:
        through.objects.using(database).bulk_create(links, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_edition_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='名称'),
        ),
        migrations.RunPython(categories_to_tags),
        migrations.RemoveField(
            model_name='edition',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
